force-app/main/default/objects/Account/fields/Webassessor_Email__c.field-meta.xml
<CustomField>
    <fullName>Webassessor_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Webassessor Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participants</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>Participant-{0000}</displayFormat>
        <label>Participant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description>Winner related to Participant</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Webassessor_Email__c.field-meta.xml
<CustomField>
    <fullName>Webassessor_Email__c</fullName>
    <description>Webassessor Email</description>
    <externalId>true</externalId>
    <label>Webassessor Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/AuthCode__c.field-meta.xml
<CustomField>
    <fullName>AuthCode__c</fullName>
    <description>AuthCode</description>
    <inlineHelpText>AuthCode</inlineHelpText>
    <label>AuthCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique Key for this Session</description>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Session__c/fields/Schedule_name__c.field-meta.xml
<CustomField>
    <fullName>Schedule_name__c</fullName>
    <label>Schedule name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Winners__c/Winners__c.object-meta.xml
<CustomObject>
    <description>Winners</description>
    <label>Winner</label>
    <nameField>
        <displayFormat>Winner-{0000}</displayFormat>
        <label>Winner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Winners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Winners__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Participant who Won</description>
    <inlineHelpText>Participant who Won</inlineHelpText>
    <label>Participant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Participant__c.Session__c</field>
            <operation>equals</operation>
            <valueField>$Source.Session__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Winners</relationshipLabel>
    <relationshipName>Winners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Winners__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description>Winner related to Session</description>
    <inlineHelpText>Winner related to Session</inlineHelpText>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Winners</relationshipLabel>
    <relationshipName>Winners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/raffleHandler.cls
/**
 * @description       : 
 * @author            : M Hamza Siddiqui
 * @group             : 
 * @last modified on  : 09-18-2021
 * @last modified by  : M Hamza Siddiqui
**/
public without sharing class raffleHandler {
    public raffleHandler() {}

    public class CustomException extends Exception {}
    
    public static CustomException createCustomException(String message) {
        CustomException ex = new CustomException(message);
        ex.setMessage(message);
        return ex;
    }

    @AuraEnabled(cacheable=true)
    public static Session__c getSession(String sessionKey) { 
        Session__c session = new Session__c();
        if(!String.isEmpty(sessionKey)){
            session = [select id, Start_Date__c,Start_Time__c, End_Time__c, Schedule_name__c, AuthCode__c from Session__c where Key__c = :sessionKey];
            if(session != null){
                List<Winners__c> winners = [Select id, Name from Winners__c where Session__c=:session.Id];
                if(winners!=null && winners.size()>0){
                    throw createCustomException('Winner: '+winners[0].Name);
                }
            }
        }
        return session;
    }

    @AuraEnabled(cacheable=true)
    public static List<Winners__c> getWinners() { 
        List<Winners__c> winners = new List<Winners__c>();
        winners = [select id, Participant__r.Name, Participant__r.Webassessor_Email__c from Winners__c];
        return winners;
    }

    @AuraEnabled(cacheable=true)
    public static List<Participant__c> getParticipants(String sessionId) { 
        List<Participant__c> participants = new List<Participant__c>();
        if(!String.isEmpty(sessionId)){
            participants = [select id, name, Session__r.Start_Time__c, Session__r.End_Time__c, Session__r.Schedule_name__c,Webassessor_Email__c from Participant__c where Session__r.Id = :sessionId];
        }

        if(participants!=null && participants.size()>0){
            List<Winners__c> winners = [Select id, Name from Winners__c where Session__c=:sessionId];
            if(winners!=null && winners.size()>0){
                throw createCustomException('Winner: '+winners[0].Name);
            }
        }
        return participants;
    }

    @AuraEnabled(cacheable=true)
    public static List<Participant__c> getParticipantsForRaffle(String sessionId) { 
        List<Participant__c> participants = new List<Participant__c>();
        Set<String> winnerEmailSet = new Set<String>();
        Map<string, List<Winners__c>> WinnersMap = new Map<string, List<Winners__c>>();
        List<Winners__c> winners = [Select id, Name, Session__c, Participant__r.Webassessor_Email__c from Winners__c];
        for (Winners__c winner : winners) {
            winnerEmailSet.add(winner.Participant__r.Webassessor_Email__c);

            if(WinnersMap.containsKey(winner.Session__c)){
                List<Winners__c> tempList = WinnersMap.get(winner.Session__c);
                tempList.add(winner);
                WinnersMap.put(winner.Session__c, tempList);
            } else {
                List<Winners__c> winnersList = new List<Winners__c>();
                winnersList.add(winner);
                WinnersMap.put(winner.Session__c, winnersList);
            }
        }
            
        if(!String.isEmpty(sessionId)){
            participants = [select id, name, Session__r.Start_Time__c, Session__r.End_Time__c, Session__r.Schedule_name__c,Webassessor_Email__c from Participant__c where Session__r.Id = :sessionId and Webassessor_Email__c not in: winnerEmailSet];
        }

        if(participants!=null && participants.size()>0){
            //List<Winners__c> winners = [Select id, Name from Winners__c where Session__c=:sessionId and Participant__r.Webassessor_Email__c NOT in :participantsSet];
            if(WinnersMap.get(sessionId)!=null && WinnersMap.get(sessionId).size()>0){
                throw createCustomException('Winner: '+WinnersMap.get(sessionId)[0].Name);
            }
        }
        return participants;
    }

    @AuraEnabled
    public static sObject createRecord(sObject data){
        try{
            insert data;
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        return data;
    }

    @AuraEnabled
    public static Id getRecordTypeIdForObject(String objName, String recTypeName) {
        return ((SObject)Type.forName(objName).newInstance())
            .getSObjectType()
            .getDescribe()
            .getRecordTypeInfosByName()
            .get(recTypeName)
            .getRecordTypeId();
    }

    @AuraEnabled
    public static Id getAccRecordTypeId(String recTypeName) {
        return Schema.SobjectType.Account.getRecordTypeInfosByName().get(recTypeName).getRecordTypeId();
    }
}