force-app/main/default/objects/Account/fields/Webassessor_Email__c.field-meta.xml
<CustomField>
    <fullName>Webassessor_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Webassessor Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participants</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>Participant-{0000}</displayFormat>
        <label>Participant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Account__r.PersonContact.MailingCity</formula>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone</description>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description>Winner related to Participant</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Webassessor_Email__c.field-meta.xml
<CustomField>
    <fullName>Webassessor_Email__c</fullName>
    <description>Webassessor Email</description>
    <externalId>true</externalId>
    <label>Webassessor Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique Key for this Session</description>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Winners__c/Winners__c.object-meta.xml
<CustomObject>
    <description>Winners</description>
    <label>Winner</label>
    <nameField>
        <displayFormat>Winner-{0000}</displayFormat>
        <label>Winner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Winners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Winners__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Participant who Won</description>
    <inlineHelpText>Participant who Won</inlineHelpText>
    <label>Participant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Participant__c.Session__c</field>
            <operation>equals</operation>
            <valueField>$Source.Session__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Winners</relationshipLabel>
    <relationshipName>Winners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Winners__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description>Winner related to Session</description>
    <inlineHelpText>Winner related to Session</inlineHelpText>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Winners</relationshipLabel>
    <relationshipName>Winners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/raffleHandlerTest.cls
@isTest
public class raffleHandlerTest {
    static testMethod void testGetSession() {
        // Test when sessionKey is provided
        Session__c testSession = new Session__c(Key__c = 'TestKey');
        insert testSession;
        Session__c result = raffleHandler.getSession('TestKey');
        //System.assertEquals('TestKey', result.Key__c);

        // Test when sessionKey is not provided
        Session__c nullResult = raffleHandler.getSession(null);
        //System.assertEquals(null, nullResult);

        // Add more test cases as needed
    }

    static testMethod void testGetWinners() {
        Session__c testSession = new Session__c();
        insert testSession;
        
        // Create test data for Winners__c
        Winners__c testWinner = new Winners__c();
        testWinner.Session__c = testSession.Id;
        insert testWinner;
        
        List<Winners__c> result = raffleHandler.getWinners();
        System.assertEquals(1, result.size());
    }

    static testMethod void testGetParticipants() {
        // Create a test session and associated participants
        Session__c testSession = new Session__c();
        insert testSession;
        Participant__c testParticipant = new Participant__c(Session__c = testSession.Id);
        //Participant__c testParticipant = new Participant__c(Session__c = testSession.Id, Webassessor_Email__c = 'test@example.com',City__c = 'Karachi',Email__c = 'hamza@pakdreamin.com',Phone__c ='+92111222333');
        
        insert testParticipant;

        List<Participant__c> result = raffleHandler.getParticipants(testSession.Id);
        System.assertEquals(1, result.size());
    }

    static testMethod void testGetParticipantsForRaffle() {
        // Create a test session, associated participants, and winners
        Session__c testSession = new Session__c();
        insert testSession;
        Participant__c testParticipant = new Participant__c(Session__c = testSession.Id);

        insert testParticipant;
        Winners__c testWinner = new Winners__c(Session__c = testSession.Id, Participant__c = testParticipant.Id);
        insert testWinner;

        List<Participant__c> result = raffleHandler.getParticipantsForRaffle(testSession.Id);
        System.assertEquals(0, result.size());
    }

    static testMethod void testCreateRecord() {
        // Create a test record
        Session__c testSession = new Session__c();
        insert testSession;

        // Create test data for sObject
        sObject testRecord = Schema.getGlobalDescribe().get('Session__c').newSObject();
		/*testRecord.put('Session__c', testSession.Id);
        testRecord.put('City__c ', 'Karachi');
        testRecord.put('Email__c ', 'hamza2@pakdreamin.com');
        testRecord.put('Phone__c ', '+92111222333');
        testRecord.put('Webassessor_Email__c', 'hamza2@pakdreamin.com');*/

        sObject result = raffleHandler.createRecord(testRecord);
        //System.assertEquals(true, result);
    }
    
    static testMethod void customException(){
        raffleHandler.createCustomException('Winner');
    }
    
    static testMethod void createParticipantTest1(){
        // Create a test record
        Session__c testSession = new Session__c();
        insert testSession;
        List<sObject> data = new List<sObject>();
        Account acc = new Account();
        acc.FirstName = 'Test';
        acc.LastName = 'Acc';
        acc.RecordTypeId = raffleHandler.getRecordTypeIdForObject('Account','Person Account');
        acc.PersonEmail = 'testacc@gmail.com';
        acc.Webassessor_Email__c = 'testacc@gmail.com';
        data.add(acc);
        raffleHandler.createParticipant(data,testSession.ID,true);
    }
    
    static testMethod void createParticipantTest2(){
        // Create a test record
        Session__c testSession = new Session__c();
        insert testSession;
        List<sObject> data = new List<sObject>();
        Account acc = new Account();
        acc.FirstName = 'Test';
        acc.LastName = 'Acc';
        acc.RecordTypeId = raffleHandler.getAccRecordTypeId('Person Account');
        acc.PersonEmail = 'testacc@gmail.com';
        acc.Webassessor_Email__c = 'testacc@gmail.com';
        data.add(acc);
        raffleHandler.createParticipant(data,testSession.ID,false);
    }
}